version: 2.1

executors:
  openjdk:
    docker:
      - image: openjdk:8u181

gradle_cache_key: &gradle_cache_key
  key: v1-dependencies-{{ checksum "buildSrc/src/main/kotlin/dependencies.kt" }}
restore_gradle_cache: &restore_gradle_cache
  restore_cache:
    <<: *gradle_cache_key
save_gradle_cache: &save_gradle_cache
  save_cache:
    <<: *gradle_cache_key
    paths:
      - ~/.gradle/wrapper
      - ~/.gradle/caches

jobs:
  build_and_check:
    executor: openjdk
    steps:
      - checkout
      - *restore_gradle_cache
      - run:
          name: Codestyle
          command: ./gradlew ktlintCheck
      - run:
          name: Assemble
          command: ./gradlew assemble
      - run:
          name: Sample run
          command: ./sample/gradlew -p ./sample/ hello
      - *save_gradle_cache

  publish_artifacts:
    executor: openjdk
    steps:
      - checkout
      - *restore_gradle_cache
      - run:
          name: Publish to Bintray
          command: ./gradlew --no-daemon :host:bintrayUpload :task:bintrayUpload

workflows:
  version: 2

  common:
    jobs:
      - build_and_check
      - publish_artifacts:
          context: "Bintray release"
          requires:
            - build_and_check
          filters:
            branches:
              only:
                - master

