version: 2.1

executors:
  openjdk:
    docker:
      - image: openjdk:8u181

gradle_cache_key: &gradle_cache_key
  key: v1-dependencies-{{ checksum "buildSrc/src/main/kotlin/dependencies.kt" }}
restore_gradle_cache: &restore_gradle_cache
  restore_cache:
    <<: *gradle_cache_key
save_gradle_cache: &save_gradle_cache
  save_cache:
    <<: *gradle_cache_key
    paths:
      - ~/.gradle/wrapper
      - ~/.gradle/caches

jobs:
  build_and_check:
    executor: openjdk
    steps:
      - checkout
      - *restore_gradle_cache
      - run:
          name: Codestyle
          command: ./gradlew ktlintCheck
      - run:
          name: Assemble
          command: ./gradlew assemble
      - run:
          name: Sample run
          command: ./sample/gradlew -p ./sample/ hello
      - *save_gradle_cache

  publish_artifacts:
    executor: openjdk
    steps:
      - checkout
      - *restore_gradle_cache
      - run:
          name: Publish to Bintray
          command: ./gradlew --no-daemon :host:bintrayUpload :task:bintrayUpload

  publish_gradle_plugin:
    executor: openjdk
    steps:
      - checkout
      - *restore_gradle_cache
      - run:
          name: Setting singup keys
          command: |
            echo "gradle.publish.key=$GRADLE_PUBLISH_KEY" >> gradle.properties
            echo "gradle.publish.secret=$GRADLE_PUBLISH_SECRET" >> gradle.properties
      - run:
          name: Publish plugin to Gradle plugin portal
          command: ./gradlew --no-daemon :plugin:publishPlugins

workflows:
  version: 2

  check:
    jobs:
      - build_and_check:
          filters:
            tags:
              ignore: /.*/

  release:
    jobs:
      - build_and_check:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - publish_artifacts:
          context: "Bintray release"
          requires:
            - build_and_check
      - publish_gradle_plugin:
          context: "Gradle plugin portal"
          requires:
            - publish_artifacts
